# Generated by Django 4.1.3 on 2022-12-13 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fichas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="diagnostico",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="registro",
            name="fecha_registro",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="registro",
            name="medico",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registro",
            name="observaciones",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="registro",
            name="paciente",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="fichas.paciente",
            ),
        ),
        migrations.AlterField(
            model_name="registro",
            name="tipo_consulta",
            field=models.CharField(default="Consulta Medica", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="registro",
            name="tratamiento",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
