# Generated by Django 4.1.2 on 2022-11-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_medico',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_paciente',
        ),
    ]
