# Generated by Django 4.1.3 on 2022-12-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichas", "0002_alter_registro_diagnostico_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apellidos",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nombres",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telefono",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
