# Generated by Django 4.1.3 on 2022-12-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichas", "0003_user_apellidos_user_nombres_user_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="apellidos",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nombres",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="telefono",
            field=models.EmailField(blank=True, default="", max_length=254, null=True),
        ),
    ]
