# Generated by Django 4.1.3 on 2022-12-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichas", "0004_alter_user_apellidos_alter_user_nombres_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telefono",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
