# Generated by Django 4.1.3 on 2022-12-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fichas", "0006_alter_registro_tipo_consulta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nombres",
        ),
        migrations.AddField(
            model_name="user",
            name="genero",
            field=models.CharField(
                choices=[("MASCULINO", "masculino"), ("FEMENINO", "femenino")],
                default="MASCULINO",
                max_length=9,
                null=True,
            ),
        ),
    ]
