services:
   django:
      build:
         dockerfile: Dockerfile
         context: .
      volumes:
         - .:/app
      ports:
         - ${DJANGO_PORT}:8000
      image: ${DJANGO_IMAGE_NAME}
      container_name: django
      command: python manage.py runserver 0.0.0.0:8000
      depends_on:
         - db
   db:
      image: '${DB_IMAGE_NAME}'
      volumes:
         - ${LOCAL_VOLUME}
      environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
         - MYSQL_DATABASE=${MYSQL_DATABASE}
         - MYSQL_USER=${MYSQL_USER}
         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      container_name: mysql
