# Generated by Django 4.1.2 on 2022-10-10 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
